export interface CredentialField {
  key: string;
  label: string;
  required: boolean;
  serverOnly: boolean;
  testable: boolean;
  category: 'ai' | 'database' | 'auth' | 'whatsapp' | 'sandbox' | 'security' | 'other';
}

export const CREDENTIAL_SCHEMA: CredentialField[] = [
  {
    key: 'GEMINI_API_KEY',
    label: 'Gemini API Key',
    required: true,
    serverOnly: false,
    testable: true,
    category: 'ai',
  },
  {
    key: 'GOOGLE_API_KEY',
    label: 'Google API Key',
    required: false,
    serverOnly: false,
    testable: true,
    category: 'auth',
  },
  {
    key: 'SUPABASE_URL',
    label: 'Supabase URL',
    required: true,
    serverOnly: false,
    testable: true,
    category: 'database',
  },
  {
    key: 'SUPABASE_PUBLISHABLE_KEY',
    label: 'Supabase Publishable Key (Anon)',
    required: true,
    serverOnly: false,
    testable: true,
    category: 'database',
  },
  {
    key: 'SUPABASE_SERVICE_ROLE_KEY',
    label: 'Supabase Service Role Key',
    required: true,
    serverOnly: true,
    testable: true,
    category: 'database',
  },
  {
    key: 'DATABASE_URL',
    label: 'Database URL',
    required: false,
    serverOnly: true,
    testable: true,
    category: 'database',
  },
  {
    key: 'FIREBASE_API_KEY',
    label: 'Firebase API Key',
    required: false,
    serverOnly: false,
    testable: true,
    category: 'auth',
  },
  {
    key: 'FIREBASE_AUTH_DOMAIN',
    label: 'Firebase Auth Domain',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'auth',
  },
  {
    key: 'FIREBASE_PROJECT_ID',
    label: 'Firebase Project ID',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'auth',
  },
  {
    key: 'FIREBASE_STORAGE_BUCKET',
    label: 'Firebase Storage Bucket',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'auth',
  },
  {
    key: 'FIREBASE_MESSAGING_SENDER_ID',
    label: 'Firebase Messaging Sender ID',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'auth',
  },
  {
    key: 'FIREBASE_APP_ID',
    label: 'Firebase App ID',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'auth',
  },
  {
    key: 'OPENAI_API_KEY',
    label: 'OpenAI API Key',
    required: false,
    serverOnly: true,
    testable: true,
    category: 'ai',
  },
  {
    key: 'OLLAMA_API_KEY',
    label: 'Ollama API Key',
    required: false,
    serverOnly: true,
    testable: true,
    category: 'ai',
  },
  {
    key: 'OLLAMA_URL',
    label: 'Ollama Base URL',
    required: false,
    serverOnly: false,
    testable: true,
    category: 'ai',
  },
  {
    key: 'OLLAMA_MODEL',
    label: 'Ollama Model Name',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'ai',
  },
  {
    key: 'OLLAMA_FALLBACK',
    label: 'Ollama Fallback Model',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'ai',
  },
  {
    key: 'MODEL',
    label: 'Default AI Model',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'ai',
  },
  {
    key: 'DIRECT_MODEL_API_URL',
    label: 'Direct Model API URL (OpenAI-compatible endpoint)',
    required: false,
    serverOnly: true,
    testable: true,
    category: 'ai',
  },
  {
    key: 'DIRECT_MODEL_API_KEY',
    label: 'Direct Model API Key',
    required: false,
    serverOnly: true,
    testable: true,
    category: 'ai',
  },
  {
    key: 'DIRECT_MODEL_NAME',
    label: 'Direct Model Name',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'ai',
  },
  {
    key: 'APP_URL',
    label: 'App URL',
    required: true,
    serverOnly: false,
    testable: false,
    category: 'other',
  },
  {
    key: 'VITE_SANDBOX_URL',
    label: 'Sandbox URL',
    required: true,
    serverOnly: false,
    testable: true,
    category: 'sandbox',
  },
  {
    key: 'SANDBOX_ROOT',
    label: 'Sandbox Root Directory',
    required: false,
    serverOnly: true,
    testable: false,
    category: 'sandbox',
  },
  {
    key: 'SANDBOX_PORT',
    label: 'Sandbox Server Port',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'sandbox',
  },
  {
    key: 'WA_AUTH_ROOT',
    label: 'WhatsApp Auth Root Directory',
    required: false,
    serverOnly: true,
    testable: false,
    category: 'whatsapp',
  },
  {
    key: 'WA_LOG_LEVEL',
    label: 'WhatsApp Log Level',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'whatsapp',
  },
  {
    key: 'WHATSAPP_ACCESS_TOKEN',
    label: 'WhatsApp Access Token',
    required: false,
    serverOnly: true,
    testable: true,
    category: 'whatsapp',
  },
  {
    key: 'WHATSAPP_PHONE_NUMBER_ID',
    label: 'WhatsApp Phone Number ID',
    required: false,
    serverOnly: false,
    testable: true,
    category: 'whatsapp',
  },
  {
    key: 'WHATSAPP_BUSINESS_ACCOUNT_ID',
    label: 'WhatsApp Business Account ID',
    required: false,
    serverOnly: false,
    testable: false,
    category: 'whatsapp',
  },
  {
    key: 'WEBHOOK_SECRET',
    label: 'Webhook Secret',
    required: false,
    serverOnly: true,
    testable: true,
    category: 'security',
  },
  {
    key: 'JWT_SECRET',
    label: 'JWT Secret',
    required: false,
    serverOnly: true,
    testable: false,
    category: 'security',
  },
  {
    key: 'WHATSAPP_SESSION_SECRET',
    label: 'WhatsApp Session Secret',
    required: false,
    serverOnly: true,
    testable: false,
    category: 'whatsapp',
  },
];

export const REQUIRED_CREDENTIALS = CREDENTIAL_SCHEMA.filter(c => c.required);
export const SERVER_ONLY_CREDENTIALS = CREDENTIAL_SCHEMA.filter(c => c.serverOnly);
export const TESTABLE_CREDENTIALS = CREDENTIAL_SCHEMA.filter(c => c.testable);
